services:
  network-conditions-publisher:
    build:
      context: ./publishers/network_conditions
      dockerfile: Dockerfile
    container_name: edge-lab-net-publisher
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped

  phase-publisher:
    build:
      context: ./publishers/network_conditions
      dockerfile: Dockerfile
    container_name: edge-lab-phase-publisher
    command: ["python", "tc_controller.py"]
    env_file:
      - .env
    environment:
      PHASE_FILE: /host-tmp/edgelab_phase
    volumes:
      - /tmp:/host-tmp:ro
    network_mode: host
    restart: unless-stopped
