version: "3.9"

services:
  network-conditions-publisher:
    build:
      context: ./publishers/network_conditions
      dockerfile: Dockerfile
    container_name: edge-lab-net-publisher
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
